### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/2R#5]
The current toolbox uses [RUnit](https://cran.rstudio.com/web/packages/RUnit/index.html) for unit testing.

Another package to perform unit tests is [testthat](https://cran.r-project.org/web/packages/testthat/index.html). It might be better suited because of better testing for warnings.

**Comment by PavelBal** [comment]
Vote for testthat.

**Comment by msevestre** [comment]
yep let's use testthat
