### ISSUE TITLE
Define Coding Standards

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/2R#52]

**Comment by msevestre** [comment]
@ju-rgen Please attach here what you have so far when you have time

**Comment by ju-rgen** [comment]
Here is my current agreement with the programmer in the traceLib,
partly a compromise between his and my traditions.
For coding styles you find different links, partly opposite, e.g. about variable and function names:
use snake style "plot_pred_obs" vs camel style "plotPredObs"
Here the programmer would like to do it differently between variables and functions to distinguish them more easily, while I would like a consistent way and distinguish by looking at the () at the end.

Links:
https://jef.works/R-style-guide/
https://google.github.io/styleguide/Rguide.xml#functiondefinition
https://style.tidyverse.org/

Our current agreement, which we plan to review in two weeks.
1.	Filenames:  
a.	Underscores separated for multiple words 
b.	All lower case 
c.	e.g., first_script.R 

2.	Organization 
a.	Operating system specific code in separate folder 
i.	System dependent utlity functions (multiple functions in same script) 
b.	Different folders for the classes, utils, API (t functions) 

3.	Internal structure 
a.	Modularization 
b.	Long functions should be avoided (more than 50 lines) 

4.	Variable names 
a.	Local 
i.	Camel case (start with lower case) 
ii.	e.g., dayOne <- 
b.	Global 
i.	Prefix g followed by upper case 
ii.	gDayOne <- 

5.	Class name 
a.	Start with upper case 
b.	Properties and methods also should start with uppercase 
c.	e.g., GetAge <-  

6.	Function names 
a.	Lower case underscore separated 
b.	Review this by end of next week! 
c.	Always should have return 
d.	e.g., to_triples <- function() 

7.	Documentation 
a.	Right amount to be determined 
b.	Don't spend too much time on that

**Comment by DiedrichC** [comment]
Don't know if this issue is the right place for this ... but anyway:

How are you going to deal with concurring R packages that do essentially the same thing? Possibly, this should be part of the coding guideline?

Concrete example: data.table vs. dplyr. Both are powerful extension to basic data.frames in R. Internally we have chosen to use data.table because we often deal with large data sets for which its superior performance is relevant. There are, however, people who claim that dplyr is more flexible - and of course its to some extend a matter of taste. But obviously, it should be standardized accross our library.

**Comment by msevestre** [comment]
@DiedrichC good point. That could be part of it or more part of the review process

In terms of coding style, I think we should ensure that we can use packages that validates styling and errors automatically when we compile them

For example I want to have a linter (https://github.com/jimhester/lintr) and a formatter (https://github.com/r-lib/styler) that will make some of the tedious `by-hand` work automated. 

That means that we might have to compromise on our coding standards, but the gain will be tremendous. We will spend some time, trying to see what can be done, and explain there again

**Comment by msevestre** [comment]
@ju-rgen 
Here please find a first definition of our coding standards
https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/CODING_STANDARDS_R.md

For the sake of time, we are going to follow what the community is suggesting (https://style.tidyverse.org/ which also seems to be what http://adv-r.had.co.nz/Style.html is suggesting) 

The big advantage is that we can use packages to automate formatting either from RStudio or with CI. No need to think about it

**Comment by PavelBal** [comment]
I am happy that we are about to agree on **not** using global variables...

Another question - quoting strings with `"` or `'`? I'd prefer `'`.

**Comment by DiedrichC** [comment]
I obviously agree with Pavel. However, maybe its worth pointing out that in contrast to many other languages in R you always by default have read-access to variables that have been defined in the parent environment of e.g. a function. (e.g. 
func1<-function(){
  text<-"Hallo world"
  func2<-function(){
    print(text)
  }
  func2()
}
)
works. Even though "test" isn't a global variable in the sense that it is defined in the global environment it sort of behaves like a global variable from within func2. I think using this feature intentionally should be explicitely rules out in the coding guideline.

**Comment by DiedrichC** [comment]
As for the " vs ' point: We have a strong preference towards using " for strings because ' is the SQL way to quote strings (And we have quite a bit of R code that queries data bases from within R).

**Comment by PavelBal** [comment]
Well, OK, I don't really have a strong opinion on quoting strings, as long as we have some standard here.

Also, I would like to include
- Using spaces after commas and before and after operands, i.e., `function(argument1 = value1, argument2 = value2)` and **not** `function(argument1=value1,argument2=value2)`

to our coding standards.

**Comment by ju-rgen** [comment]
Does that mean, that we will always work with function, not with scripts?
And about the scope of variables: having a function defined in another function is something different than calling a function from another function. I would assume, that we won't define functions in other functions so often.
I would like to know, which alternatives are in place for "Singletons", e.g. a DB-connection, a log-File, a trace-Object other than global variables. Could you please describe?

**Comment by DiedrichC** [comment]
If you define a function from within a script (e.g. by sourcing the function definition) the same thing applies. --> Everything that is then defined within the script will be visible from within the function (read only). 
> text<-"Hallo World"
> func1<-function(){print(text)}
> func1()
[1] "Hallo World"

**Comment by ju-rgen** [comment]
About coding style:
How to name fields/properties and methods of a class? I opt for Pascal casing.

For variable names I prefer camelCase over snake_case.

**Comment by msevestre** [comment]
As far as "" vs '' or space between //  etc.. All of that will be taken care of automatically using the prettier addin that I mentioned earlier that ensure correct formatting

Example:
```R
# BEFORE
func1<-function(param1,param2){
  text<-'Hallo world'
  func2<-function(){
        print(text)
  }
  func2()
}

# AFTER

func1 <- function(param1, param2) {
  text <- "Hallo world"
  func2 <- function() {
    print(text)
  }
  func2()
}

````
** Spacing, single vs double quote etc.. " will be implemented consistently automatically

**Comment by msevestre** [comment]
As far as @DiedrichC concerns about closure

> it sort of behaves like a global variable from within func2. I think using this feature intentionally should be explicitely rules out in the coding guideline.

I strongly disagree with this statement. This variable is not global at all. It is in the scope of the function defining it and will be released as soon as the function is finished. The concept of closure is a **key** concept in functional programming and asking people not to use it is in my opinion not a good idea.

I agree however that closure can have weird effects sometimes. But it also allows for encapsulation of methods that one does not want to expose to the outside. Not much of a problem for a `package` because one can decide which methods will be exported but still a good way to ensure that people are not callign a method within a package that is intended for private use only

**Comment by DiedrichC** [comment]
Pretty ;-)

**Comment by msevestre** [comment]
as far as dealing with global variables (because sometimes there is a need for them such as the active theme, a default options etc.. ) I have created an issue here
https://github.com/Open-Systems-Pharmacology/2R/issues/64

Let's try to come up with a neat way to deal with this

**Comment by PavelBal** [comment]
>Does that mean, that we will always work with function, not with scripts?

@ju-rgen What do you mean? You are calling functions within scripts...

> ** Spacing, single vs double quote etc.. " will be implemented consistently automatically

OK cool.

**Comment by msevestre** [comment]
As far as casing is concerned.
Unless there is a clear reason that is more than personal preferences, let's try to follow `https://style.tidyverse.org/` to the T. It is fully documented, well explained and we do not have to reinvent the wheel. I am not used to code variable `like_that` either coming from a .NET world, but this is quite enjoyable to read and I can adapt

An advantage is also that we can use tooling to verify that we adhere to the coding standard without having to do anything. (or at least we will if we have time to implement)

**Comment by PavelBal** [comment]
Agree to stick to the standards of tidyverse.

**Comment by ju-rgen** [comment]
@PavelBal: I personally would like to go without scripts, where possible - just using functions.
E.g. having a function workflow.R instead of just a script.
But I assume, that the users like scripts, because all the variables used there are in global environment and visible to them. And that's easier than returning everything, which is of interest, explicitely.

**Comment by msevestre** [comment]
In a package, there is no script. Everything has to be a function. So this will depend on which "hat" you have on so to speak:
 
* User of one of our package => then a script is clearly possible and probably what most user would do to solve a specific problem using our packages 
* developer of one package  => In that case, you have no choice but use function

**Comment by ju-rgen** [comment]
About coding style: In the R universe exist different coding styles. Two of the top five (by searching for "R coding style") suggest the camelStyle for variable & function names.
So it is matter of personal taste, which of the common coding styles to follow.
Have a look at: 
https://jef.works/R-style-guide/
https://google.github.io/styleguide/Rguide.xml

**Comment by PavelBal** [comment]
May I ask why 

> Only use return() for early returns. Otherwise, rely on R to return the result of the last evaluated expression.

? I find it more convenient to always use `return(object)`, as one can easy see what the function returns without "evaluating" the last expression. Also it is a good indicator whether we expect something in return or not.

**Comment by ju-rgen** [comment]
I strongly agree with Pavel.

**Comment by msevestre** [comment]
@all: In order to track all proposed changes, I'd suggest creating one issue for each change request. 
I have created the label "Coding Standards" that we can refer to. Then we can agree on each issue and move on. Thanks

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/2R/issues?q=is%3Aissue+is%3Aopen+label%3A%22Coding+Standards%22

**Comment by msevestre** [comment]
@all: For any new requests, please create another issue and we can decide to either integrate or disregard the proposed changes.
