### ISSUE TITLE
Function and variable naming: Snake case or camelCase

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/2R#70]
```R
parameter_list <- get_parameters_from(simulation)
```

OR

```R
parameterList <- getParametersFrom(simulation)
```

/cc @Open-Systems-Pharmacology/rdev

**Comment by PavelBal** [comment]
I like snake case more, but camelCase seems to be more common in R.

I still vote for snake.

**Comment by ju-rgen** [comment]
You already know: I like camelCase more.
When there is a decision please let Thomas Gaub know to inform Jeevan!

**Comment by Yuri05** [comment]
for me: `parameterList <- getParametersFrom(simulation)`

**Comment by msevestre** [comment]
camelCase it is
https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/CODING_STANDARDS_R.md#modifications-from-tidyverse-coding-standards

https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/CODING_STANDARDS_R.md#object-names
