### ISSUE TITLE
Return: Do we allow implicit return or not?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/2R#71]
/cc @Open-Systems-Pharmacology/rdev

**Comment by PavelBal** [comment]
Yes.

**Comment by ju-rgen** [comment]
??? I thought, Pavel was voting for allowing an **explicit** return statement!
At least I do.

**Comment by PavelBal** [comment]
Aaaah yes, thank you @ju-rgen. Got confused here.

**Comment by msevestre** [comment]
The question is not do we allow an explicit return statement. The question is do we allow IMPLICIT return statements. 

>I find it more convenient to always use return(object), as one can easy see what the function returns without "evaluating" the last expression. Also it is a good indicator whether we expect something in return or not.

The question is do we want to FORCE one way or the other. Maybe we do not need to be some limiting here

**Comment by msevestre** [comment]
I have updated the coding standard to propose the usage of a return() statement as a preferred way, still allowing however the implicit return for simple functions. 

https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/CODING_STANDARDS_R.md#functions
